### ISSUE TITLE
Implement images in README.md

### ISSUE THREAD

**Issue by Samuel-de-Oliveira** [LucasAlfare/FLTimer#1]
Hello.

Well, I can see it's a great project, but I have a suggestion to place some images of the program for a easy overview.

well I hope this useful.

**Comment by LucasAlfare** [comment]
Thanks for the feedback ^^

For now I think is not important to provide some images due to the development, mainly because the UI, still active.

Once the application achieve a better stable version, at leats on the UI, we should to improve more usability and even showcase to it.

There's also a simple module aimed to work at terminal/command line. This module don't have to much in special to show up, anyway, let me see what do you think.

**Comment by Samuel-de-Oliveira** [comment]
That's okay, I'm glad to know about the development. And the terminal module looks great too, I hope this project get on.

**Comment by LucasAlfare** [comment]
Added some presentation images of the current development stage in [50810d8](https://github.com/LucasAlfare/FLTimer/commit/50810d838583978ce7ba298634150f70e85744b7), over the `view_modeling` branch.
